"""Parche 1.8 add_cascade_delete_loan_request_items_loan_request

Revision ID: 6970f4e12ed7
Revises: b26801b2ddb0
Create Date: 2026-03-15 20:45:23.727524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6970f4e12ed7'
down_revision: Union[str, Sequence[str], None] = 'b26801b2ddb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('loan_request_items_loan_request_id_fkey'), 'loan_request_items', type_='foreignkey')
    op.drop_constraint(op.f('loan_request_items_device_id_fkey'), 'loan_request_items', type_='foreignkey')
    op.create_foreign_key(None, 'loan_request_items', 'devices', ['device_id'], ['id'])
    op.create_foreign_key(None, 'loan_request_items', 'loan_requests', ['loan_request_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loan_request_items', type_='foreignkey')
    op.drop_constraint(None, 'loan_request_items', type_='foreignkey')
    op.create_foreign_key(op.f('loan_request_items_device_id_fkey'), 'loan_request_items', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('loan_request_items_loan_request_id_fkey'), 'loan_request_items', 'loan_requests', ['loan_request_id'], ['id'])
    # ### end Alembic commands ###
