"""Parche 1.3 a app/models/inventory.py; remueve comment de DeviceStatusLog

Revision ID: f6658e72ebb2
Revises: e6adcacbbec2
Create Date: 2026-03-10 03:32:10.675738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6658e72ebb2'
down_revision: Union[str, Sequence[str], None] = 'e6adcacbbec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_status_logs', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_status_logs', sa.Column('comment', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
