"""Parche 1.4 generando userRoles como ORM de SQLAlchemy

Revision ID: e4d746f30449
Revises: f6658e72ebb2
Create Date: 2026-03-11 09:27:11.238138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4d746f30449'
down_revision: Union[str, Sequence[str], None] = 'f6658e72ebb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
