"""Parche 1.5 add_cascade_delete_device_product

Revision ID: 070dac9706ea
Revises: e4d746f30449
Create Date: 2026-03-15 00:45:43.455455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '070dac9706ea'
down_revision: Union[str, Sequence[str], None] = 'e4d746f30449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('devices_product_id_fkey'), 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key(op.f('devices_product_id_fkey'), 'devices', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
